# GUI file generated by GUI Pie, developed by Jabberwock
# https://apps.microsoft.com/store/detail/gui-pie/9P5TH15LZSL7


import os
import sys
import subprocess
import math
from tkinter import *
from tkinter import ttk
import tkinter.font
try:
  from PIL import ImageTk, Image, ImageOps
except:
  print('Installing PIL.')
  subprocess.check_call(['pip', 'install', 'pillow'])
  print('Done.')
  from PIL import ImageTk, Image, ImageOps

if __name__ == "__main__":
  v_tracker_gui = Tk()
else:
  v_tracker_gui = Tk()
v_tracker_gui.title('v_tracker_gui')
dpi = 96
v_tracker_gui.geometry('400x400')
v_tracker_gui.grid_propagate(False)
for x in range(10):
  Grid.columnconfigure(v_tracker_gui, x, weight=1, uniform='row')
  Label(v_tracker_gui, width = 1, bg = '#FFFFFF').grid(row = 0, column = x, sticky = N+S+E+W)
for y in range(10):
  Grid.rowconfigure(v_tracker_gui, y, weight=1, uniform='row')
  Label(v_tracker_gui, width = 1, bg = '#FFFFFF').grid(row = y, column = 0, sticky = N+S+E+W)
v_tracker_gui.configure(background='#FFFFFF')

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~WIDGETS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

v_tracker_gui.BackgroundImageOriginal = Image.open(r'C:/Users/Ayaansh_Joshi/Downloads/full-res-for-display.png')
v_tracker_gui.BackgroundImageImage = ImageOps.exif_transpose(v_tracker_gui.BackgroundImageOriginal)
v_tracker_gui.BackgroundImageImage = ImageTk.PhotoImage(v_tracker_gui.BackgroundImageImage.resize((math.ceil(400 * dpi / 96), math.ceil(400 * dpi / 96)), Image.Resampling.LANCZOS))
v_tracker_gui.BackgroundImage = Label(v_tracker_gui, image = v_tracker_gui.BackgroundImageImage, width = 1, height = 1, bg = '#FFFFFF')
v_tracker_gui.BackgroundImage.grid(row = 0, column = 0, columnspan = 10, rowspan = 10, sticky = N+S+E+W)
v_tracker_gui.insert_text = Entry(v_tracker_gui, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
v_tracker_gui.insert_text.grid(row = 3, column = 3, columnspan = 4, rowspan = 1, sticky = N+S+E+W)
v_tracker_gui.insert_text.insert(0, "")
def defocus(event):
  event.widget.master.focus_set()
v_tracker_gui.select_option_dropdown = ttk.Combobox(v_tracker_gui, values = ['add','read',], width = 1, state = 'readonly')
v_tracker_gui.select_option_dropdown.grid(row = 1, column = 2, columnspan = 3, rowspan = 1, sticky = N+S+E+W)
v_tracker_gui.select_option_dropdown.bind('<FocusIn>', defocus)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~BUTTONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def runEvent1(argument):
  if not(__name__ == '__main__'):
    from main import Event1
    try:
      Event1(argument)
    except TypeError:
      Event1()
v_tracker_gui.run_option_button = Button(v_tracker_gui, text = "run", font = ('Arial', 16), width = 1, height = 1, fg = '#FFFFFF', command = lambda: runEvent1('run_option_button'), bg = '#000000')
v_tracker_gui.run_option_button.grid(row = 1, column = 7, columnspan = 1, rowspan = 1, sticky = N+S+E+W)
v_tracker_gui.help_button = Button(v_tracker_gui, text = "help", font = ('Arial', 16), width = 1, height = 1, fg = '#FFFFFF', command = lambda: runEvent1('help_button'), bg = '#000000')
v_tracker_gui.help_button.grid(row = 3, column = 0, columnspan = 2, rowspan = 1, sticky = N+S+E+W)
v_tracker_gui.info_button = Button(v_tracker_gui, text = "info", font = ('Arial', 16), width = 1, height = 1, fg = '#FFFFFF', command = lambda: runEvent1('info_button'), bg = '#000000')
v_tracker_gui.info_button.grid(row = 3, column = 8, columnspan = 2, rowspan = 1, sticky = N+S+E+W)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~HELPER FUNCTIONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def initModules():
  raise Exception('This main file is outdated. Script main.py must be updated to reflect the changes in GUI Pie v3.')
def init():
  from main import Event1
v_tracker_gui.initModules = initModules
def hide():
  v_tracker_gui.withdraw()
def show():
  v_tracker_gui.deiconify()
def hideAllWidgets():
    v_tracker_gui.insert_text.grid_remove()
    v_tracker_gui.run_option_button.grid_remove()
    v_tracker_gui.help_button.grid_remove()
    v_tracker_gui.info_button.grid_remove()
    v_tracker_gui.select_option_dropdown.grid_remove()
    v_tracker_gui.result_of_option.grid_remove()
v_tracker_gui.hideAllWidgets = hideAllWidgets
def showAllWidgets():
    v_tracker_gui.insert_text.grid()
    v_tracker_gui.run_option_button.grid()
    v_tracker_gui.help_button.grid()
    v_tracker_gui.info_button.grid()
    v_tracker_gui.select_option_dropdown.grid()
    v_tracker_gui.result_of_option.grid()
v_tracker_gui.showAllWidgets = showAllWidgets
def run():
  global dimensions
  dimensions = [0,0]
  if __name__ != "__main__":
    init()
  resizeEvent(None)
  v_tracker_gui.mainloop()
v_tracker_gui.run = run
v_tracker_gui.hide = hide
v_tracker_gui.show = show


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~CUSTOM-WIDGETS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

v_tracker_gui.result_of_option = Label(v_tracker_gui, text = 'result', font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#55FF55')
v_tracker_gui.result_of_option.grid(row = 6, column = 1, columnspan = 8, rowspan = 3, sticky = N+S+E+W)
dimensions = [v_tracker_gui.winfo_width(), v_tracker_gui.winfo_height()]
def resize():
  global v_tracker_gui, dimensions
  if v_tracker_gui.winfo_width() != dimensions[0] or v_tracker_gui.winfo_height() != dimensions[1]:
    v_tracker_gui.run_option_button.config(wraplength = math.ceil(v_tracker_gui.winfo_width() * 1 / 10) + 2)
    v_tracker_gui.help_button.config(wraplength = math.ceil(v_tracker_gui.winfo_width() * 2 / 10) + 2)
    v_tracker_gui.info_button.config(wraplength = math.ceil(v_tracker_gui.winfo_width() * 2 / 10) + 2)
    v_tracker_gui.BackgroundImageOriginal = Image.open(r'C:/Users/Ayaansh_Joshi/Downloads/full-res-for-display.png')
    v_tracker_gui.BackgroundImageImage = ImageOps.exif_transpose(v_tracker_gui.BackgroundImageOriginal)
    v_tracker_gui.BackgroundImageImage = ImageTk.PhotoImage(v_tracker_gui.BackgroundImageImage.resize((v_tracker_gui.winfo_width(), v_tracker_gui.winfo_height()), Image.Resampling.LANCZOS))
    v_tracker_gui.BackgroundImage.config(image = v_tracker_gui.BackgroundImageImage)
    dimensions = [v_tracker_gui.winfo_width(), v_tracker_gui.winfo_height()]

eventID = None
v_tracker_gui.resizeDelay = 100
def resizeEvent(event):
  global eventID
  if eventID:
    v_tracker_gui.after_cancel(eventID)
  eventID = v_tracker_gui.after(v_tracker_gui.resizeDelay, resize)
v_tracker_gui.bind('<Configure>', resizeEvent)
if __name__ == "__main__":
  v_tracker_gui.run()
